### ISSUE TITLE
Knitr of Analysis.Rmd gets a read table error

### ISSUE THREAD

**Issue by AustinLVB** [post2web/DDSCaseStudy1#8]
When I pulled down the Master updates and tried to Knitr the code, I got a read table error.  Anyone else get this?  
 |......                                                           |   9%
  ordinary text without R code

  |............                                                     |  18%
label: unnamed-chunk-1

processing file: Analysis.Rmd
Quitting from lines 29-32 (Analysis.Rmd) 
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read.table -> file
Execution halted

**Comment by post2web** [comment]
Are you knitting the Analysis.Rmd or the Makefile.Rmd?

**Comment by post2web** [comment]
To me it looks like you don't have the file data/merged_data.csv created. You need to run the Makefile.Rmd first

**Comment by post2web** [comment]
Should I close the issue?
